# Generated by Django 5.1.2 on 2024-10-31 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_remove_contact_groups'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='groups',
            field=models.ManyToManyField(related_name='contacts', to='organizations.group', verbose_name='گروه\u200cها'),
        ),
    ]
