# Generated by Django 5.1.2 on 2024-11-05 17:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('text_messages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام برنامه پیامکی')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
                ('groups', models.ManyToManyField(blank=True, to='organizations.group', verbose_name='گروه\u200cهای هدف')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='text_messages.message', verbose_name='پیام مرتبط')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization', verbose_name='سازمان مرتبط')),
                ('users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='کاربران هدف')),
            ],
            options={
                'verbose_name': 'برنامه پیامکی',
                'verbose_name_plural': 'برنامه\u200cهای پیامکی',
            },
        ),
    ]
