# Generated by Django 5.1.2 on 2024-11-05 18:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_contact_groups'),
        ('organizations', '0001_initial'),
        ('sender', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
                ('assigned_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='کاربر مسئول')),
                ('contacts', models.ManyToManyField(related_name='tasks', to='contacts.contact', verbose_name='مخاطبین')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization', verbose_name='سازمان مرتبط')),
                ('sms_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sender.smsprogram', verbose_name='برنامه پیامکی مرتبط')),
            ],
            options={
                'verbose_name': 'وظیفه کاربر',
                'verbose_name_plural': 'وظایف کاربران',
            },
        ),
    ]
