# Generated by Django 5.1.2 on 2024-10-23 17:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام سازمان یا مجموعه')),
                ('responsible_name', models.CharField(max_length=150, verbose_name='نام و نام خانوادگی مسئول')),
                ('responsible_phone', models.CharField(max_length=15, verbose_name='شماره تماس مسئول')),
                ('national_id', models.CharField(max_length=10, verbose_name='کد ملی مسئول')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات درباره سازمان یا مجموعه')),
            ],
            options={
                'verbose_name': 'سازمان',
                'verbose_name_plural': 'سازمان\u200cها',
            },
        ),
    ]
