# Generated by Django 5.1.2 on 2024-10-23 17:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات درباره سازمان یا مجموعه'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='national_id',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='کد ملی مسئول'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='responsible_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='نام و نام خانوادگی مسئول'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='responsible_phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='شماره تماس مسئول'),
        ),
    ]
