# Generated by Django 5.1.2 on 2025-04-03 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='sms_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='کد پیامک'),
        ),
    ]
