# Generated by Django 5.1.2 on 2024-10-22 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='', max_length=15, unique=True, verbose_name='phone number'),
        ),
    ]
