# Generated by Django 5.1.2 on 2024-11-08 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_gender_user_organization_alter_user_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_access_contacts',
            field=models.BooleanField(default=False, help_text='Designates whether this user has access to manage contacts.', verbose_name='access to contacts'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_access_groups',
            field=models.BooleanField(default=False, help_text='Designates whether this user has access to manage groups.', verbose_name='access to groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_access_messages',
            field=models.BooleanField(default=False, help_text='Designates whether this user has access to messages.', verbose_name='access to messages'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_access_sms_program',
            field=models.BooleanField(default=False, help_text='Designates whether this user has access to SMS program.', verbose_name='access to SMS program'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_access_users',
            field=models.BooleanField(default=False, help_text='Designates whether this user has access to manage users.', verbose_name='access to users'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_send_bulk_sms',
            field=models.BooleanField(default=False, help_text='Designates whether this user can send bulk SMS messages.', verbose_name='send bulk SMS'),
        ),
    ]
