# Generated by Django 5.1.2 on 2024-11-08 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_can_access_contacts_user_can_access_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_add_contacts',
            field=models.BooleanField(default=False, help_text='Designates whether this user can add contacts through the app.', verbose_name='add contacts through app'),
        ),
    ]
