# Generated by Django 5.1.2 on 2025-02-02 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_can_add_contacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='JihadiGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام گروه جهادی')),
                ('leader_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام مسئول')),
                ('leader_national_id', models.CharField(blank=True, max_length=10, null=True, verbose_name='کد ملی مسئول')),
                ('leader_contact_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='شماره تماس مسئول')),
                ('deputy_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام مسئول دوم')),
                ('deputy_contact_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='شماره تماس مسئول دوم')),
                ('service_province', models.CharField(blank=True, max_length=255, null=True, verbose_name='استان محل خدمت')),
                ('service_city', models.CharField(blank=True, max_length=255, null=True, verbose_name='شهرستان محل خدمت')),
            ],
            options={
                'verbose_name': 'گروه جهادی',
                'verbose_name_plural': 'گروه\u200cهای جهادی',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='jihadi_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.jihadigroup', verbose_name='گروه جهادی'),
        ),
    ]
