# Generated by Django 5.1.2 on 2024-11-05 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('text_messages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='groups',
            field=models.ManyToManyField(blank=True, to='organizations.group', verbose_name='گروه\u200cهای مرتبط'),
        ),
    ]
